// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyTest.Infrastructure.Data;

#nullable disable

namespace MyTest.Infrastructure.Migrations
{
    [DbContext(typeof(DogDbContext))]
    partial class DogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MyTest.Application.Entities.Breed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("FemaleWeightMax")
                        .HasColumnType("int");

                    b.Property<int>("FemaleWeightMin")
                        .HasColumnType("int");

                    b.Property<bool>("Hypoallergenic")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LifeMax")
                        .HasColumnType("int");

                    b.Property<int>("LifeMin")
                        .HasColumnType("int");

                    b.Property<int>("MaleWeightMax")
                        .HasColumnType("int");

                    b.Property<int>("MaleWeightMin")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Breed", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
